version: "3.9"

services:

  mysql:
    image: mysql:8
    container_name: mlops-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mlops
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mlflow:
    image: python:3.11
    container_name: mlflow-server
    working_dir: /mlflow
    volumes:
      - ./mlruns:/mlflow/mlruns
      - ./mlflow.db:/mlflow/mlflow.db
    command: >
      sh -c "pip install mlflow &&
             mlflow server
             --backend-store-uri sqlite:///mlflow.db
             --default-artifact-root ./mlruns
             --host 0.0.0.0
             --port 5000"
    ports:
      - "5000:5000"

  api:
    build: ./api
    container_name: churn-api
    depends_on:
      - mysql
      - mlflow
    ports:
      - "8000:8000"
    restart: always

volumes:
  mysql_data:




